name = "mukoko"
compatibility_date = "2025-05-01"
main = "./worker/index.js"

# Assets configuration for React SPA
[assets]
directory = "./dist"
binding = "__STATIC_CONTENT"

# Production Environment Variables (Default)
[vars]
NODE_ENV = "production"
USE_FALLBACK_CONFIG = "false"
LOG_LEVEL = "info"
MAX_CACHE_SIZE = "100MB"
CACHE_TTL = "3600"
RSS_TIMEOUT = "10000"
MAX_ARTICLES_PER_SOURCE = "100"
ANALYTICS_ENABLED = "true"
CLOUDFLARE_IMAGES_ENABLED = "true"
ADMIN_KEY = "mukoko-admin-2025-secure-key"
# Supabase Configuration
VITE_SUPABASE_URL = "https://huilmzajhiqcuzonbaps.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1aWxtemFqaGlxY3V6b25iYXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzAyMjIsImV4cCI6MjA3MDc0NjIyMn0.G5C9Swbb1tXEjyhkI98PlQxZ_2OUXI1vD0Eh8Q81KZU"
# MongoDB Configuration (for high-frequency operations)
MONGODB_URI = "mongodb+srv://mukoko:SecurePass2024@mukoko-cluster.mongodb.net/"
MONGODB_DB_NAME = "mukoko_interactions"
# Enhanced features
ENABLE_REAL_TIME_CHAT = "true"
ENABLE_PUSH_NOTIFICATIONS = "true" 
ENABLE_ANALYTICS_TRACKING = "true"
ENABLE_CONTENT_RECOMMENDATIONS = "true"
# Role-based access configuration
ROLES_ENABLED = "true"
DEFAULT_ROLE = "creator"
ADMIN_ROLES = "admin,super_admin,moderator"
CREATOR_ROLES = "creator,business-creator,author"

# Production KV Namespaces
[[kv_namespaces]]
binding = "CONFIG_STORAGE"
id = "73d709fa9f6a414fbea359cda40ec7db"
preview_id = "f11d764e7d824243a4193d74aff9107f"

[[kv_namespaces]]
binding = "CACHE_STORAGE"
id = "3933ee4aaa8246fd933b61eb1111528f"
preview_id = "8b7a8a0285a74250910e917ba83a18bf"

[[kv_namespaces]]
binding = "USER_STORAGE"
id = "494ec8445cd842ae8a7c50b5245fcc42"
preview_id = "59985587dd834c75b9ab393e31f2cf17"

[[kv_namespaces]]
binding = "NEWS_STORAGE" 
id = "472195d9dcb948b7a73c10b2716375ca"
preview_id = "8c7b7c28e9fa4abc971935876cf9ca26"

# Production D1 Database
[[d1_databases]]
binding = "USER_DB"
database_name = "mukoko_users"
database_id = "b6204614-2cf1-47ed-b9e4-1fbbeb09fe01"

# Production Analytics Engine - THE CORRECT 3 DATASETS
[[analytics_engine_datasets]]
binding = "CATEGORY_CLICKS"
dataset = "category_clicks"

[[analytics_engine_datasets]]
binding = "NEWS_INTERACTIONS"
dataset = "news_interactions"

[[analytics_engine_datasets]]
binding = "SEARCH_QUERIES"
dataset = "search_queries"

# Durable Objects for real-time features
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "USER_SESSIONS"
class_name = "UserSession"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "UserSession"]

# Cron Triggers for Background Refresh
[triggers]
crons = ["0 * * * *"]

# Smart Placement for Global Performance
[placement]
mode = "smart"

# Production Routes
[[routes]]
pattern = "app.mukoko.com/*"
zone_name = "mukoko.com"

[[routes]]
pattern = "www.mukoko.com/*"
zone_name = "mukoko.com"

# Preview Environment (for local development)
[env.preview]
name = "mukoko-preview"

[env.preview.vars]
NODE_ENV = "development"
USE_FALLBACK_CONFIG = "true"
LOG_LEVEL = "debug"
ANALYTICS_ENABLED = "false"
CLOUDFLARE_IMAGES_ENABLED = "true"
MAX_CACHE_SIZE = "25MB"
CACHE_TTL = "900"
RSS_TIMEOUT = "8000"
MAX_ARTICLES_PER_SOURCE = "50"
CLOUDFLARE_IMAGES_ACCOUNT_ID = "125a2dfbc21f76a25c980609609e8218"
CLOUDFLARE_IMAGES_TOKEN = "pVe0DAJWrCvXIcm7BzAymwR0vW4-oBF9VGiODLJN"
ADMIN_KEY = "preview-admin-key"
# Supabase Configuration
VITE_SUPABASE_URL = "https://huilmzajhiqcuzonbaps.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1aWxtemFqaGlxY3V6b25iYXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzAyMjIsImV4cCI6MjA3MDc0NjIyMn0.G5C9Swbb1tXEjyhkI98PlQxZ_2OUXI1vD0Eh8Q81KZU"
# Role-based access configuration
ROLES_ENABLED = "true"
DEFAULT_ROLE = "creator"
ADMIN_ROLES = "admin,super_admin,moderator"
CREATOR_ROLES = "creator,business-creator,author"
# Enhanced MongoDB Configuration
MONGODB_URI = "mongodb://localhost:27017"
MONGODB_DB_NAME = "mukoko_preview"
ENABLE_REAL_TIME_CHAT = "false"
ENABLE_PUSH_NOTIFICATIONS = "false"
ENABLE_ANALYTICS_TRACKING = "false"
ENABLE_CONTENT_RECOMMENDATIONS = "false"

# Preview KV Namespaces (use preview_id for local development)
[[env.preview.kv_namespaces]]
binding = "CONFIG_STORAGE"
id = "73d709fa9f6a414fbea359cda40ec7db"
preview_id = "f11d764e7d824243a4193d74aff9107f"

[[env.preview.kv_namespaces]]
binding = "CACHE_STORAGE"
id = "3933ee4aaa8246fd933b61eb1111528f"
preview_id = "8b7a8a0285a74250910e917ba83a18bf"

[[env.preview.kv_namespaces]]
binding = "USER_STORAGE"
id = "494ec8445cd842ae8a7c50b5245fcc42"
preview_id = "59985587dd834c75b9ab393e31f2cf17"

[[env.preview.kv_namespaces]]
binding = "NEWS_STORAGE" 
id = "472195d9dcb948b7a73c10b2716375ca"
preview_id = "8c7b7c28e9fa4abc971935876cf9ca26"

# Preview D1 Database
[[env.preview.d1_databases]]
binding = "USER_DB"
database_name = "mukoko_users"
database_id = "b6204614-2cf1-47ed-b9e4-1fbbeb09fe01"

# Preview Durable Objects for real-time features
[[env.preview.durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[env.preview.durable_objects.bindings]]
name = "USER_SESSIONS"
class_name = "UserSession"

# Preview Analytics Engine - Disabled for local development
# [[env.preview.analytics_engine_datasets]]
# binding = "CATEGORY_CLICKS"
# dataset = "category_clicks"
