// Analytics tracking hook - Auto-generated by analytics-setup.sh
import { useCallback } from 'react'

export function useAnalytics() {
  const trackArticleView = useCallback(async (article) => {
    try {
      const params = new URLSearchParams({
        id: article.id || 'unknown',
        source: article.source || 'unknown',
        category: article.category || 'general'
      })
      await fetch(`/api/analytics/article-view?${params}`)
    } catch (error) {
      console.error('Analytics tracking failed:', error)
    }
  }, [])

  const trackSearch = useCallback(async (query, filters = {}) => {
    try {
      const params = new URLSearchParams({
        q: query,
        category: filters.category || 'all',
        source: filters.source || 'all'
      })
      await fetch(`/api/analytics/search?${params}`)
    } catch (error) {
      console.error('Search analytics failed:', error)
    }
  }, [])

  const trackCategoryClick = useCallback(async (category, source = null) => {
    try {
      const params = source ? `?source=${source}` : ''
      await fetch(`/api/analytics/category/${category}${params}`)
    } catch (error) {
      console.error('Category analytics failed:', error)
    }
  }, [])

  return {
    trackArticleView,
    trackSearch,
    trackCategoryClick
  }
}
