name = "harare-metro"
compatibility_date = "2025-05-01"
main = "./worker/index.js"

[assets]
directory = "./dist/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "NEWS_STORAGE"
id = "472195d9dcb948b7a73c10b2716375ca"
preview_id = "8c7b7c28e9fa4abc971935876cf9ca26"

# Analytics Engine Configuration
[[analytics_engine_datasets]]
binding = "NEWS_ANALYTICS"
dataset = "news_interactions"

[[analytics_engine_datasets]]
binding = "SEARCH_ANALYTICS"
dataset = "search_queries"

[[analytics_engine_datasets]]
binding = "CATEGORY_ANALYTICS"
dataset = "category_clicks"

[triggers]
crons = ["0 * * * *"]  # Changed from every 6 hours to every hour

[placement]
mode = "smart"

# Production environment with custom domain
[[routes]]
pattern = "www.hararemetro.co.zw/*"
zone_name = "hararemetro.co.zw"

# Staging environment configuration
[env.staging]
name = "harare-metro-staging"
[[env.staging.routes]]
pattern = "staging.hararemetro.co.zw/*"
zone_name = "hararemetro.co.zw"